# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-15 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='datePosted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
